name: iso_build
on:
  workflow_dispatch:
  schedule:
    - cron:  '30 2 * * *'

jobs:
  print-token:
    permissions: write-all
    name: print-token
    environment: dev
    # needs: pre-pkr
    runs-on: ubuntu-20.04

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Get registration token
        id: getRegToken
        run: |
          curl -X POST -H \"Accept: application/vnd.github.v3+json\"  -H 'Authorization: token ${{ secrets.GITHUB_TOKEN }}' https://api.github.com/repos/myprofile/myrepo/actions/runners/registration-token
  prepare-release:
    runs-on: ubuntu-20.04
    permissions: write-all
    steps:
      - 
        uses: styfle/cancel-workflow-action@0.9.0
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
      - 
        id: time
        uses: nanzm/get-time-action@v1.1
        with:
          format: 'YYYYMMDDHHmm'
    outputs:
      release_tag: ${{ steps.time.outputs.time }}
  build-release:
    runs-on: ubuntu-20.04
    permissions: write-all
    needs: [prepare-release]
    strategy:
      matrix:
        EDITION: [kde]
        BRANCH: [stable]
        SCOPE: [full]
    steps:
      - 
        uses: styfle/cancel-workflow-action@0.9.0
        with:
          access_token: ${{ secrets.github.token }}
      - 
        id: time
        uses: nanzm/get-time-action@v1.1
        with:
          format: 'YY.MM'   
      -
        name: image-build-upload
        uses: manjaro/manjaro-iso-action@main
        
        with:
          edition: ${{ matrix.edition }}
          access_token: ${{ secrets.github.token }}
          branch: ${{ matrix.branch }}
          scope: ${{ matrix.scope }}
          version: ${{ steps.time.outputs.time }}-development
          kernel: linux67
          code-name: "Nightly-Build"
          release-tag: ${{ needs.prepare-release.outputs.release_tag }}
      -
        name: rollback
        if: ${{ failure() || cancelled() }}
        run: |
          echo ${{ secrets.github.token }} | gh auth login --with-token
          gh release delete ${{ needs.prepare-release.outputs.release_tag }} -y --repo ${{ github.repository }}
